export const REQUESTED_URL = "http://localhost:3000"
export const USER_REQUESTED_URL = "http://localhost:3000/user"
export const ORGANIZATION_REQUESTED_URL = "http://localhost:3000/organization"
export const ADMIN_REQUESTED_URL = "http://localhost:3000/admin"
export const VIDEO_CALL_REQUESTED_URL = "http://localhost:3000/videoCall"